import Head from "next/head";
import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import clsx from "clsx";

function Tier({ name, price, href, features, featured = false }) {
  return (
    <article>
      <div className="tier">
        <h2 className="tier__title">{name}</h2>
        <ul className="tier__feature-list">
          <li className="tier__list-item">1 domain</li>
          <li className="tier__list-item">1 domain</li>
          <li className="tier__list-item">1 domain</li>
          <li className="tier__list-item">1 domain</li>
        </ul>
        <p className="tier__price">
          {price}
          <span>/mo</span>
        </p>
      </div>
      <Button
        href={href}
        color={featured ? 'white' : 'blue'}
        aria-label={`Get started with the ${name} plan for ${price}`}
      >
        Get started
      </Button>
    </article>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Test
        <Container>
          <div className="pricing-plans">
            <Tier name="Free" price="$9" href="/" featured  />
          </div>
        </Container>
      </main>
    </>
  );
}
