import Head from "next/head";
import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import clsx from "clsx";

function Tier({ name, price, href, features, featured = false }) {
  return (
    <article className={clsx("tier", featured && "tier--mirrored")}>
      <h2 className="tier__title">{name}</h2>
      <ul className="tier__feature-list">
        {features.map((feature) => (
          <li key={feature} className="tier__list-item">
            {feature}
          </li>
        ))}
      </ul>
      <p className="tier__price">
        {price}
        <span>/mo</span>
      </p>
      <Button
        href={href}
        color={featured ? "white" : "blue"}
        aria-label={`Get started with the ${name} plan for ${price}`}
      >
        Get started
      </Button>
    </article>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hosting plans</h1>
        <Container>
          <div className="pricing-plans">
            <Tier
              name="Free"
              features={[
                "Send 10 quotes and invoices",
                "Connect up to 2 bank accounts",
                "Track up to 15 expenses per month",
                "Manual payroll support",
                "Export up to 3 reports",
              ]}
              price="$9"
              href="/"
            />
           <Tier
              name="Free"
              features={[
                "Send 10 quotes and invoices",
                "Connect up to 2 bank accounts",
                "Track up to 15 expenses per month",
                "Manual payroll support",
                "Export up to 3 reports",
              ]}
              price="$9"
              href="/"
              featured
            />
            <Tier
              name="Free"
              features={[
                "Send 10 quotes and invoices",
                "Connect up to 2 bank accounts",
                "Track up to 15 expenses per month",
                "Manual payroll support",
                "Export up to 3 reports",
              ]}
              price="$9"
              href="/"
            />
          </div>
        </Container>
      </main>
    </>
  );
}
